# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = NodeBase
DESTDIR = ../Win32/Debug
QT += core gui
CONFIG += staticlib
DEFINES += QT_DLL NODEBASE_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
HEADERS += ./nodebase.h \
    ./nodewidgetbase.h
SOURCES += ./nodebase.cpp \
    ./nodewidgetbase.cpp
