# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = XMLParamsLoader
DESTDIR = ../Win32/Debug
QT += core
CONFIG += staticlib
DEFINES += QT_DLL XMLPARAMSLOADER_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
HEADERS += ./xmlparamsloader.h
SOURCES += ./xmlparamsloader.cpp
