# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = Sensor
DESTDIR = ../Win32/Debug
QT += core gui
CONFIG += staticlib
DEFINES += QT_DLL SENSOR_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
HEADERS += ./sensor.h \
    ./sensorwidget.h
SOURCES += ./sensor.cpp \
    ./sensorwidget.cpp
